name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        uses: arunamballa/arunamballa/.github/actions/blog-post-workflow@master
        with:
          feed_list: 'https://medium.com/feed/@arunamballa24'
